### ISSUE TITLE
Can't require('node-chrome-runner')

### ISSUE THREAD

**Issue by willscott** [uProxy/node-chrome-runner#2]
the current package throws an error when required, since the main script is not properly indexed.

This appears to be because the [`.gitignore`](https://github.com/uProxy/node-chrome-runner/blob/master/.gitignore#L20) lists the build directory, and no `.npmignore` exists to override that, so the npm package doesn't include the compiled script either.

**Comment by iislucas** [comment]
Thanks!

 fixed in https://github.com/uProxy/node-chrome-runner/commit/7d23c23b6947a95bcd90c821235c9650ac483878

(npm published 0.0.5)
